voxpupuli/puppet-openssl

templates/cert.cnf.erb

SHA1 is now deprecated and showing warnings in modern browsers.  (Resolves #36)

templates/cert.cnf.erb: Use sha256 instead of sha1 by default

---

lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/type/x509_cert.rb
manifests/certificate/x509.pp
spec/unit/puppet/provider/x509_cert/openssl_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb

Subject additional names were used inproperly.
Now we generate certificate with SAN's if they
were passed as an additional names to manifest.

Fix san use in certificate

---

README.md
lib/puppet/provider/dhparam/openssl.rb
lib/puppet/type/dhparam.rb
manifests/dhparam.pp
spec/defines/openssl_dhparam_spec.rb
spec/unit/puppet/provider/dhparam/openssl_spec.rb
spec/unit/puppet/type/dhparam_spec.rb

You should be using a stronger-than-default dhparam for modern TLS configuration to mitigate https://weakdh.org/
This makes it easy to do so.

dhparam: add

---

Gemfile
lib/puppet/provider/x509_cert/openssl.rb
spec/unit/puppet/provider/x509_cert/openssl_spec.rb

Add checking commonName and subjectAltName in old certificate
if it exists. In other way we could not regenerate a new certificate
if any of these fields change.

Change cert existance logic

---

lib/puppet/provider/x509_cert/openssl.rb
spec/unit/puppet/provider/x509_cert/openssl_spec.rb

If the `inifile` gem isn't installed on the node we get the following error from Puppet agent:
> Error: Could not autoload puppet/provider/x509_cert/openssl: cannot load such file -- inifile
> Error: Could not autoload puppet/type/x509_cert: Could not autoload puppet/provider/x509_cert/openssl: cannot load such file -- inifile
> Error: Failed to apply catalog: Could not autoload puppet/type/x509_cert: Could not autoload puppet/provider/x509_cert/openssl: cannot load such file -- inifile
This happens so early in the process that we can't use Puppet to install the required gem.
This patch changes the code so that the inifile gem isn't loaded until it is actually needed. This has two benefits:
1. If the code that requires the inifile gem isn't actually used in this deployment, we don't need …

Fix failure to load inifile causing Puppet agent to fail.

---

lib/puppet/provider/x509_cert/openssl.rb

When creating an ssl cert that uses an ip address as an altname the cert was being recreated every puppet run. This was due to the fact that the x509_cert provider recognizes the altname as "IP Address" but the cert.cnf requires that it is defined as such (where 127.0.0.1 is the desired ip):
`subjectAltName = IP:127.0.0.1`
This resulted in the provider thinking that the cert changed because "IPAddress:127.0.0.1" != "IP:127.0.0.1"

altnames can represent ip addresses

---

lib/facter/openssl_version.rb
spec/unit/openssl_version_spec.rb

Fixes #62 
RHEL 6:
```
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
CentOS:
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

fixes #62 - error resolving openssl_version on RHEL 6

---

lib/puppet/provider/ssl_pkey/openssl.rb
lib/puppet/type/ssl_pkey.rb
manifests/certificate/x509.pp
spec/defines/openssl_certificate_x509_spec.rb

The section `Integer()` was required as puppet returned 
```
Error: Could not set 'present' on ensure: Neither PUB key nor PRIV key: not enough data at 172:/etc/puppet/environments/intg/modules/openssl/manifests/certificate/x509.pp
```
When using
```
ssl_pkey { $_key:
ensure   => $ensure,
password => $password,
size     => 4096,
}
```
It was running as `OpenSSL::PKey::RSA.new('4096')` (note the quotes).  I guess it is the type validation (`/newvalues /\d+/`) which return content as a string.

Add argument key_size to openssl::certificate::x509

---

lib/puppet/type/x509_cert.rb
lib/puppet/type/x509_request.rb
manifests/certificate/x509.pp

This could very well be an abomination (sysadmin here), but this seems to work for us.
When using openssl::certificate::x509, if the config changes, the CSR and cert are regenerated.

handle refresh (RE: #71)

---

lib/puppet/type/ssl_pkey.rb

When setting the authentication in Puppet for a ssl_pkey :
```
ssl_pkey { "${ssl_dir}/${service_name}":
ensure          => present,
size            => 2048,
authentication  => 'dsa',
password        => 'test'
}
```
I get the following error : `Error: Unknown authentication type 'dsa' when setting authentication`
I tried with and without quotes/double quotes.
I use Puppet 3.8.5, with Ruby 1.8.7.
After looking at the code, it seems the comparison is done with a symbol :
```
def self.generate_key(resource)
if resource[:authentication] == :dsa
OpenSSL::PKey::DSA.new(resource[:size])
elsif resource[:authentication] == :rsa
OpenSSL::PKey::RSA.new(resource[:size])
else
raise Puppet::Error,
"Unknown authentication type '#{resource[:authentication]}'"
end
end
```
Replacing `if …

Error: Unknown authentication type 'dsa' when setting authentication

---

README.md
manifests/export/pem_cert.pp
manifests/export/pem_key.pp

Add openssl::export::pem_cert to export PEM certs from PKCS12.
Add openssl::export::pem_key to export PEM certs from PKCS12.
Update README.md to reflect this addition.

Add definitions to export PEM cert/key from PKCS12 container

---

manifests/dhparam.pp

In lib/puppet/type/dhparam.rb, we set the default for the dhparam type
to false, so to keep konsistent, the default value for the define
should also be false.

Make the $fastmode parameter for openssl::dhparam default to false.

---

.gitignore
lib/puppet/provider/x509_request/openssl.rb
lib/puppet/type/x509_request.rb
manifests/certificate/x509.pp

Issue #83  is the upstream issue request for this pull request.  It adds a new field named `unencrypted` to the x509_req type and the Openssl::certificates::x509 class.  This in turns goes to the provider. When turned on (default is off to preserve existing behaviour), it will pass the `-nodes` argument to the underlying openssl command, resulting in a key that can be used by OpenLDAP.

Changes to support unencrypted CSRs

---

templates/cert.cnf.erb

Since version 58, Chrome no longer trusts certificates that don't contain a SAN. This means Chrome now displays a security error for certificates generated by puppet-openssl (even after you've added it to your trust store) because it doesn't include a SAN.
See #44 for the root cause.
This change appears to be all that's required to fix the issue. It tells OpenSSL to include the x509 data in the certificate, not only in the CSR.
Props @bijanvakili for investigation into this almost two years ago in #44.

Add the x509_extensions directive to support SAN in certificate

---

spec/defines/openssl_certificate_x509_spec.rb
spec/defines/openssl_dhparam_spec.rb
templates/cert.cnf.erb

* Fix variable reference in `templates/cert.cnf.erb` to fix spec tests.
* The error message for **Absolutepath** is different between Puppet 4 and Puppet 5, so spec tests can't check for the exception type anymore, just the error string.

Fix spec tests

---

lib/puppet/provider/ssl_pkey/openssl.rb
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/provider/x509_request/openssl.rb
lib/puppet/type/ssl_pkey.rb
lib/puppet/type/x509_cert.rb
lib/puppet/type/x509_request.rb
spec/unit/puppet/provider/ssl_pkey/openssl_spec.rb
spec/unit/puppet/type/ssl_pkey_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb
spec/unit/puppet/type/x509_request_spec.rb

This change adds the ability to generate EC key pairs. There is a default curve secp384r1. The list of curves is not pre enumerated for validation as the list of possible curves is way too long. And it would require code changes when new curves are added.

Add ability to generate Elliptic Curve key pairs

---

lib/facter/openssl_version.rb
spec/unit/openssl_version_spec.rb

el8 may have an OpenSSL version that doesn't match the current version regex,
e.g. `OpenSSL 1.1.1c FIPS 28 May 2019`. With this PR the regex now allows the
version string to contain ` FIPS` between the version number and date.
``` ruby
openssl_version = 'OpenSSL 1.1.1c FIPS  28 May 2019'
%r{^OpenSSL ([\w\.\-]+)( FIPS)?([ ]+)([\d\.]+)([ ]+)([\w\.]+)([ ]+)([\d\.]+)}.match(openssl_version)[1]
```

Allow openssl_version regex to match more FIPS versions

---

data/common.yaml
data/os/OpenBSD.yaml
manifests/init.pp
manifests/packages.pp
metadata.json
spec/classes/openssl_spec.rb

* add OpenBSD to supported in metadata.json
* make package_name optional, since OpenBSD installs libressl
which part of the system, not available as package
* adapt spec tests for OpenBSD without package installation
* add spec test check for package name to be installed

add support for OpenBSD

---

data/os/OpenBSD.yaml
manifests/configs.pp
spec/classes/configs_spec.rb
templates/cert.cnf.epp

The new class openssl::configs create openssl.conf files.
The generation bases on a new .epp template since epp can
use parameters which was easier to integrate.
closes: #41

add class to generate configs

---

manifests/configs.pp

That was a bit fast to remove...
this reverts ae510aabcd72c60080c698687f8cbaa5402c98ec
from pull request #116 (remove dependencies since we have autorequire)
and adds the dependencies between openssl config file and cert generations.
the autorequire mentioned in the the original commit, meant the
newly available autorequire in the defined types. But that one is
an autorequire for the directory where we put the file to generate, not
the configuration file !

readd dependencies to class to generate configs

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitlab-ci.yml
.pdkignore
.rubocop.yml
.travis.yml
.vscode/extensions.json
Gemfile
Rakefile
appveyor.yml
metadata.json
spec/spec_helper.rb

This is converting to latest PDK and updating dependencies and requirements to latest supported versions.
Trivia:
* Puppet 5.5 reached EOL in January 2021 [[1](https://puppet.com/docs/puppet/5.5/about_agent.html)]
* PDK removed Puppet 5 from test environments [[puppetlabs/pdk-templates#403](https://github.com/puppetlabs/pdk-templates/pull/403)]

update pdk, dependencies and requirements

---

lib/puppet/functions/cert_aia_caissuers.rb
spec/functions/cert_aia_caissuers_spec.rb

In the case of deferred evaluation of cert_aia_caissuers, when the argument does not point to an existing and readable file, the function will fail and stop the agent.
This adds an appropriate test case and fix for this issue.

incorrect behaviour of cert_aia_caissuers if file does not exists

---

manifests/init.pp
metadata.json

The `$package_ensure` default needs to be changed due to https://github.com/puppetlabs/puppetlabs-stdlib/pull/1196.

allow stdlib 8.0.0

---

lib/facter/openssl_version.rb
spec/unit/openssl_version_spec.rb

As described in #134, the custom fact openssl_version does not work on EL8 OpenSSL 1.1.1k.
There is a subtle change in the output of `openssl version`: there are two spaces instead of one after the version number...

fix openssl_version on EL8 OpenSSL 1.1.1k

---

lib/puppet/provider/cert_file/posix.rb

Accept server certificates signed by trusted third-parties when receiving remote certificates via https.
When getting a remote certificate via https, by default the http client trusts the PuppetCA only, thus downloading files from a server using certificates signed by a third-party would fail. This patch allows the Puppet HTTP client to trust a server using a certificate signed by any CA trusted by the system.

Allow cert_file to download certificates via https

---

manifests/configs.pp
templates/cert.cnf.erb

Fixing ERB syntax in templates/cert.cnf.erb -- line 17 uses `<% if $req_ext` while line 38 uses `<% if @req_ext`. As a result, line 17 never evaluates to true.
No issues filed currently, but verified with ewoud on Slack that the `$` syntax is just wrong for ERB.

templates/cert.cnf.erb should use @, not $

---

manifests/certificate/x509.pp

As mentioned here : 5.3.1 Key Length
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf
"The length of the modulus n should be at least 2000 bits for a period of use until 2023 and at least 3000 bits if used beyond 2023."

Enlarge key size based on new security requirement

---

lib/puppet/provider/x509_request/openssl.rb
spec/unit/puppet/provider/x509_request/openssl_spec.rb

Failed when I renamed my branch with #154, sry for the inconvenience.
Still just makes x509_request consistent with x509_cert.

refactor x509_request to be consistent with x509_cert provider

---

REFERENCE.md
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/type/x509_cert.rb
manifests/certificate/x509.pp
spec/unit/puppet/provider/x509_cert/openssl_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb

This Pull requests adresses parts of #152 and should allow users to provide a CA certificate and key to sign generated certificates.
n/a

add ability to certificate provider to get signed against a CA cert

---

templates/cert.cnf.epp

Adds IPv6 support for SANs by moving to Stdlib::IP::Address subtype

move from own regex to stdlib ip type adding ipv6 support for SANS

---

manifests/packages.pp
metadata.json

* Require puppetlabs-stdlib 9.x

Require puppetlabs-stdlib 9.x

---

REFERENCE.md
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/type/x509_cert.rb
spec/unit/puppet/provider/x509_cert/openssl_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb

This fixes an issue handling request extensions in the x509_cert provider when issueing self-signed certificates.
Along with #179, this Fixes #178

Fix handling of request extensions in x509_cert type and provider

---

lib/puppet/type/x509_cert.rb

Generate types fails for x509_cert due to missing type require.
Fixes #197

Add missing require so that generate types works.

---

manifests/export/pem_cert.pp
manifests/export/pem_key.pp
manifests/export/pkcs12.pp

Remove unnecessary single quotes for passin and passout parameter.
Also fixes a bug, where the quotation is interpreted as a part of the password

export/{pem_cert,pem_key,pkcs12}: `passin`, `passout`: use `shellquote()` instead of single quotation marks

---

README.md
REFERENCE.md
manifests/export/pem_cert.pp
manifests/export/pem_key.pp
manifests/export/pkcs12.pp
spec/defines/openssl_export_pem_cert_spec.rb

Add possibility to switch the underlying Execs to "refreshonly" mode and hand over subscriptions to resource(s) as parameter. This fixes also a bug when p12 file is not renewed after the input file changed. Backward compatibility fully given.
Fixes #131

feat: refreshable exports

---

REFERENCE.md
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/type/x509_cert.rb
manifests/certificate/x509.pp
spec/defines/openssl_certificate_x509_spec.rb
spec/unit/puppet/provider/x509_cert/openssl_spec.rb

This is a rebase of https://github.com/voxpupuli/puppet-openssl/pull/188/files?diff=unified&w=1

Allow passing a CA key password when signing a cert

---

examples/x509_cert.pp
spec/acceptance/x509_cert_spec.rb

This is way faster to generate compared to the default 3072. Otherwise our CI runs for ages.

acceptance tests: use 1024 bit keys

---

REFERENCE.md
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/provider/x509_request/openssl.rb
lib/puppet/type/x509_cert.rb
lib/puppet/type/x509_request.rb
spec/unit/puppet/provider/cert_file/posix_spec.rb
spec/unit/puppet/provider/ssl_pkey/openssl_spec.rb
spec/unit/puppet/provider/x509_cert/openssl_spec.rb
spec/unit/puppet/provider/x509_request/openssl_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb
spec/unit/puppet/type/x509_request_spec.rb

This utilizes a method where OpenSSL itself determines the encryption type rather than a static parameter. This is more flexible because it requires fewer parameters to be specified.
Prior to that it does several cleanups to the tests.

Use OpenSSL::PKey.read to read private keys

---

lib/puppet/provider/ssl_pkey/openssl.rb
spec/unit/puppet/provider/ssl_pkey/openssl_spec.rb

This updates the algorithm for password encryption in certificates from the outdated des3 to aes-256-cbc.

password encryption: switch from des3->aes-256-cbc

---

REFERENCE.md
lib/puppet/provider/ssl_pkey/openssl.rb
lib/puppet/type/ssl_pkey.rb
spec/unit/puppet/provider/ssl_pkey/openssl_spec.rb
spec/unit/puppet/type/ssl_pkey_spec.rb

DSA is considered insecure by now. FIPS 186-5 forbids signing with DSA and on modern distributions have started to drop support for it.

Drop DSA key support

---

lib/puppet/provider/ssl_pkey/openssl.rb
spec/unit/puppet/provider/ssl_pkey/openssl_spec.rb

In OpenSSL 3 the `OpenSSL::PKey::EC` class has become immutable. In a pure OpenSSL 3 world the right thing would be to use `OpenSSL::PKey.generate_key` but that's not supported in OpenSSL 1.  Calling `.generate` is compatible with both 1 and 3.
It also stops mocking the actual calls to see if they will work. prime239v1 is replaced by prime256v1 because on Fedora 39+ only the latter is available.
I only tested this locally on my desktop. If it passes, it's a pure enhancement and I'd expect make Puppet 8 support possible.

Support OpenSSL 3

---

manifests/certificate/x509.pp

Use private key created before, not the default value.
Fixes #185

Use private_key parameter when creating certificate

---

manifests/export/pem_cert.pp
manifests/export/pem_key.pp
manifests/export/pkcs12.pp
metadata.json
spec/defines/openssl_export_pem_cert_spec.rb

Puppet 7.9 introduced support to pass an array, which avoids using a shell altogether. This simplifies the code because there's no more need to escape and join options.

Pass openssl commands as an array

---

REFERENCE.md
lib/puppet/provider/dhparam/openssl.rb
lib/puppet/provider/openssl.rb
lib/puppet/provider/ssl_pkey/openssl.rb
lib/puppet/provider/x509_cert/openssl.rb
lib/puppet/provider/x509_request/openssl.rb
lib/puppet/type/dhparam.rb
lib/puppet/type/ssl_pkey.rb
lib/puppet/type/x509_cert.rb
lib/puppet/type/x509_request.rb
spec/unit/puppet/type/dhparam_spec.rb
spec/unit/puppet/type/ssl_pkey_spec.rb
spec/unit/puppet/type/x509_cert_spec.rb
spec/unit/puppet/type/x509_request_spec.rb

This adds the possibility to directly specify user/group and mode for key, request, cert and dh.
In a second step the manifests could be simplified (no need for file resources setting permissions).

add user/group/mode parameter to custom types
