voxpupuli/puppet-openssl

- manifests/certificate/x509.pp
This makes it easy to restrict daemons to reading their keys only.
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
> Add key_mode/group/owner parameters

- README.md
- manifests/init.pp
- manifests/packages.pp
> Allow to set package version

- manifests/packages.pp
- spec/classes/openssl_spec.rb
> Manage ca-certificates package on redhat too

- lib/puppet/type/dhparam.rb
Signed-off-by: Maksim Malchuk <maksim.malchuk@gmail.com>
> Fix validation of the size parameter

- lib/puppet/provider/x509_cert/openssl.rb
- spec/unit/puppet/provider/x509_cert/openssl_spec.rb
This aims to fix https://github.com/camptocamp/puppet-openssl/issues/63
> Use Puppet::Util::Inifile instead of Inifile

- lib/puppet/provider/dhparam/openssl.rb
- lib/puppet/type/dhparam.rb
- manifests/dhparam.pp
- spec/defines/openssl_dhparam_spec.rb
> Fastmode, Default Keysize increased, path defaults to name 

- README.md
> Update dhparams example in README.md

- manifests/export/pem_cert.pp
- manifests/export/pem_key.pp
- manifests/export/pkcs12.pp
> in_pass, out_pass and chaincert params to Optional[String]

- README.md
> Rework README.md/add correct badges

- spec/defines/openssl_certificate_x509_spec.rb
- spec/defines/openssl_dhparam_spec.rb
- spec/defines/openssl_export_pem_cert_spec.rb
> Tests: Use modern rspec syntax

- .github/CONTRIBUTING.md
- .msync.yml
- .rubocop.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 5.3.0

- manifests/certificate/x509.pp
- spec/defines/openssl_certificate_x509_spec.rb
> fix logic bug with extkeyusage and altnames

- CHANGELOG.md
- metadata.json
> Release 3.1.1

- metadata.json
> Drop EoL Ubuntu 14.04,16.04,18.04

- metadata.json
also contains https://github.com/voxpupuli/puppet-openssl/pull/210
> Drop EoL RedHat 6 and 7 support

- .github/workflows/ci.yml
- .sync.yml
- examples/x509_cert.pp
- spec/acceptance/dhparam_spec.rb
- spec/acceptance/x509_cert_spec.rb
- spec/spec_helper_acceptance.rb
- spec/support/acceptance/matchers/match_without_whitespace.rb
Based on https://github.com/voxpupuli/puppet-openssl/pull/191 because we need a proper testing matrix.
> Add basic acceptance tests for the existing examples

- REFERENCE.md
- lib/puppet/provider/x509_cert/openssl.rb
- lib/puppet/type/x509_cert.rb
- manifests/certificate/x509.pp
- metadata.json
- spec/defines/openssl_certificate_x509_spec.rb
- spec/unit/puppet/provider/x509_cert/openssl_spec.rb
> Add OracleLinux 8 & 9 support

- REFERENCE.md
- lib/puppet/provider/x509_cert/openssl.rb
- lib/puppet/type/x509_cert.rb
- manifests/certificate/x509.pp
- metadata.json
- spec/defines/openssl_certificate_x509_spec.rb
- spec/unit/puppet/provider/x509_cert/openssl_spec.rb
> Add Rocky Linux 8 & 9 support

- metadata.json
> Add Archlinux support

- lib/puppet/provider/x509_cert/openssl.rb
- spec/unit/puppet/provider/x509_cert/openssl_spec.rb
> Fix expression that looks like boolish logic

- manifests/configs.pp
- spec/classes/configs_spec.rb
The parameters 
- configs::mode
- configs::group
- configs::owner
have no effect
closes: #236
> fix default configs file ownership

- examples/export_pkcs12_from_key.pp
- spec/acceptance/pkcs12_spec.rb
> Add acceptance test for PKCS#12 generation with password

- examples/export_pkcs12_from_key.pp
- spec/acceptance/pkcs12_spec.rb
> openssl::certificate::pkcs12: Add test for x509 without password

- manifests/export/pkcs12.pp
This makes the code just a bit shorter.
> openssl::export::pkcs12: cleanup if condition

- examples/export_pem_from_pkcs12.pp
- spec/acceptance/export_pem_from_pkcs12.rb
> openssl::export::pem_key: Add acceptance tests
